### ISSUE TITLE
Vague description of referenced queries 

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#2567] opened 2020-10-20 05:33 UTC
This description could be more clear.
In the example, Query1 is a none loading query. Readers might think that making it a loading query, the data will be cached, and this is wrong. Please make this more clear.
PBI Dataflow is mention as a way to cash the data. Yes this is true if query1 is a loading query/entity, but not if it's a none loading query/entity

Note:
I always see a referenced query (query1) as compatible with a SQL sub-query and it would be good (if this is the correct analogy) if Microsoft also does this analogy. I know that in some cases (like where the formula FW kicks in), the internal engine treats codes differently depending on if it's a referenced query or if you embed the code in the referencing query (query2), but my guess is that this is a mistake in the implementation of the formula FW and not by design

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb0fcf5f-584d-9825-7f9e-20b4cf290f73
* Version Independent ID: f010d1f9-3f7d-c7ef-68ba-4cd133e4c7fb
* Content: [Referencing Power Query queries - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/power-query-referenced-queries)
* Content Source: [powerbi-docs/guidance/power-query-referenced-queries.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/power-query-referenced-queries.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by mihart** [comment] 2020-10-21 05:53
Thanks for your comment, @erapade  . This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment] 2020-12-30 22:30
Thanks @erapade - we will take your feedback into consideration. #please-close

**Closed by peter-myers** 2020-12-30 22:30 UTC
Labels: Pri2, assigned-to-author, doc-bug, powerbi-desktop/subsvc, powerbi/svc

**Comment by erapade** [comment] 2020-12-31 17:07
@peter-myers Just so that I understand the process. How can “closing” be the same as "taking it into consideration”. Either you close it (and never re-visit) the issue, or you start working on it and let us know when done

**Comment by kfollis** [comment] 2021-01-04 22:59
@erapade - Thanks for your feedback. We’ve reviewed the article and determined it reads technically correct and describes the subject matter as intended by the author. No additional changes will be made at this time. However, as a Git Issue, even when closed, your feedback is kept with the article. If similar feedback is received from other users, we will review again and take steps necessary to improve clarity and accuracy.
