### ISSUE TITLE
Evaluation Context / Bookmarks / Oct. 2018 Release

### ISSUE THREAD

**Issue by joerobert06** [MicrosoftDocs/powerbi-docs#408] opened 2018-11-08 13:49 UTC
I have noticed that I have lost the ability to hold an evaluation context when using bookmarks to toggle between visualizations on the same page. For example if I was to select a bar on a bar chart and switch between visuals, the selected context goes back to the original state. “Data” is unchecked under data properties and so I am not sure why I’m seeing this response. I used this technique very frequently prior to the oct release. Your assistance is very appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Using bookmarks in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks#feedback)
* Content Source: [powerbi-docs/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bookmarks.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment] 2018-11-09 22:40
Hi @joerobert06 -- I see this is a duplicate of your other comment, right? You've done the right thing by posting in the community. I'm going to close this. Thanks and I hope they can figure out what's not working!

**Closed by maggiesMSFT** 2018-11-09 22:40 UTC
