### ISSUE TITLE
Python with Anaconda

### ISSUE THREAD

**Issue by smjanalytics** [MicrosoftDocs/powerbi-docs#379] opened 2018-10-30 20:34 UTC
Power BI seems to have issues with finding packages when Python has been installed using Anaconda. It would be nice if this page could identify how to set up installation so that it works with Anaconda.

I've found a couple of similar issues in postings like this:
https://stackoverflow.com/questions/52885101/anaconda-in-windows-with-power-bi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Running Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-scripts)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by mihart** [comment] 2018-10-31 07:55
Hi @smjanalytics 
Thank you for your question.  I've assigned this to the author.  He will contact you shortly.
Take care,
Michele

**Comment by lanedance** [comment] 2019-04-09 12:34
Same I cant make power bi python 'work at home or work. No chance of changing python at work with IT policies either. Appreciate any help. Just upgraded to March 2019 and not even the simplest python code works.

**Comment by lanedance** [comment] 2019-04-09 12:34
Same I cant make power bi python 'work at home or work. No chance of changing python at work with IT policies either. Appreciate any help. Just upgraded to March 2019 and not even the simplest python code works.

**Comment by eliungs** [comment] 2019-05-15 04:12
Still an issue.

**Comment by lanedance** [comment] 2019-05-15 06:00
I downloaded and installed winPython, plays with Power BI fine, straight after install. Couldn't get it to work with Anaconda.

**Comment by maggiesMSFT** [comment] 2019-05-15 17:41
Hi, all -- this issue is assigned to the writer. In the meantime, I recommend checking the community site to see if anyone there has an answer.
https://community.powerbi.com/

**Comment by mbast100** [comment] 2019-06-05 18:14
any news from this issue ?

**Comment by otarb** [comment] 2019-07-01 18:18
Hello,

Could you please share more details about your environment? Are you using 32 or 64 bit version of each: Windows, Power BI, Python? Which version of Anaconda do you have? Those things will help us reproduce issue on our end and pinpoint the root cause.

Please make sure right installation is selected on Power BI options page (File -> Options and settings -> Options -> Python scripting)
![image](https://user-images.githubusercontent.com/17887981/60457630-6080fb00-9bf1-11e9-8120-11add4702273.png)

In linked stackoverflow question (https://stackoverflow.com/questions/52885101/anaconda-in-windows-with-power-bi) it looks like user has another step they have to take after opening python executable to set up their environment (running .bat script). Power BI takes user provided python executable (provided through settings page) and executes user provided script directly. If there are any extra steps required for setting up environment, those should be done inside the script itself.

**Comment by XavierParedes** [comment] 2019-07-03 15:01
@otarb , I have the same problem. I’m using a 64-bit version of Windows, a 64-bit version of Power BI and Python 3.7.3.
I propose the following solution to fix this problem if your engineers can apply this for the next release: In the Detected Python home directories, if a user chooses Other, they have to browse to a location where the Python installation resides. However, the user cannot type a custom location. Can your engineers enable users to type a custom location manually instead of having to choose from the Browse button?
After Anaconda gets installed, 2 shortcut files get created on the user’s end: Anaconda Powershell Prompt and Anaconda Prompt (i.e., the CMD version). By right-clicking on either .lnk file and choosing to see its Properties, you can see the Target path (e.g., %windir%\System32\cmd.exe “/K” C:\Users\[username]\AppData\Local\Continuum\anaconda3\Scripts\activate.bat C:\Users\[username]\AppData\Local\Continuum\anaconda3\), which is how the Anaconda virtual environment gets activated (and likely where the user from that StackOverflow question got his information from). That Target path is what I suspect needs to be passed in as the “Detected Python home directory” in Power BI so that the virtual environment would run and all of the dependencies would be recognized. Have your engineers test this as well to see if this is working as desired.

**Comment by mesa123123** [comment] 2019-08-06 04:17
Whats happening with this issue?

**Comment by RobLW** [comment] 2019-10-08 10:22
I am using Miniconda (don't want the bloat ware of anaconda) Like all good pythonists, I setup a new environment for my PowerBI and install the modules needed.
However when I try to run a script in powerbi it tells me it is having issues importing ft2font from matplotlib. When I load the python environment in my console I can import it just perfectly fine. 

-----
DataSource.Error: ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\<MyLogin>\.conda\envs\Analytics\lib\site-packages\matplotlib\__init__.py", line 205, in <module>
    _check_versions()
  File "C:\Users\<MyLogin>\.conda\envs\Analytics\lib\site-packages\matplotlib\__init__.py", line 190, in _check_versions
    from matplotlib import ft2font
ImportError: DLL load failed: The specified module could not be found.
------

**Comment by RobLW** [comment] 2019-10-08 10:37
SOLUTION : Although I use miniconda I'm sure the same is for most on here. Your install most likely has an environment setup. Power BI Desktop, by default, will use the Python.exe found from your system environment variables. So for example in windows 10, I went to "edit system environment variables", and added my python environment to my USERS path variable. Not the system one (which had the default python install). PowerBI will now pick up the python found in the users path before the system path version, and will see all your modules installed there. Problem though, is that this is system wide now.

**Comment by otarb** [comment] 2019-11-14 00:21
@XavierParedes currently we don't allow selecting custom executable, but that is something we might consider doing in the future. thanks for suggestion! in the meantime, if python environment requires some steps to be ready, we suggest calling those steps in the script itself.

@RobLW In the options tab, under Python scripting, you are able to see exact folder path from which PowerBI will try to call an Python executable and have an option to point it to custom path. Looking at this value, you can know for certain which Python installation will be used for execution. For installations that we detected on the machine, we will add options in the dropdown.

![image](https://user-images.githubusercontent.com/17887981/68815828-5e17be80-0631-11ea-9a5f-af16b32ed67b.png)

**Comment by otarb** [comment] 2019-11-14 00:22
#please-close @otarb

**Closed by otarb** 2019-11-14 00:22 UTC
Labels: assigned-to-author, doc-enhancement, powerbi/svc, pri1
