### ISSUE TITLE
Greyed Out fields

### ISSUE THREAD

**Issue by oex-pbi** [MicrosoftDocs/powerbi-docs#1839] opened 2020-02-13 12:55 UTC
At the end of this page, it mentions 'Greyed out fields aren't editable' - can you offer more explaination to this. 

Scenario - Using 'Common Data Service connector' in desktop, get data from CDS tables -&gt; Create Parameters fro Entity Name and Dynamics instance URL -&gt; add to Source in Advanced Editor -&gt; Publish to service, fields are greyed out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d00a910-94df-cb0d-d8e5-81160bd2f569
* Version Independent ID: 4925a925-42fd-8deb-d702-25cd929a5849
* Content: [Edit parameter settings in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-parameters#feedback)
* Content Source: [powerbi-docs/service-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-parameters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment] 2020-02-13 21:30
Hi @o365dev , thanks for reaching out to us with your question. I am forwarding on to the author of the article you mentioned for consideration.

**Comment by rG-tom** [comment] 2020-04-28 16:46
@paulinbar where did you get to with this? A number of parameters are greyed out for me, and mine are just for excel file connections.

Thanks,

**Comment by mtthsbrr** [comment] 2020-05-10 23:41
For me only "non-any" parameter types show up as expected (not greyed out) in Power BI Service. Whenever I tried something like "any" type, its ending up being greyed out in the dataset > settings > parameters section. In Power BI Desktop everything works so is this a bug or a by design behavior in Power BI Service?

**Comment by teddybercovitz** [comment] 2021-03-08 21:11
It's a service limitation for dataset parameters, we currently do not support type "Any" or "Binary" parameters in the service for security reasons.

**Comment by maggiesMSFT** [comment] 2021-03-09 02:40
Thanks, @teddybercovitz !
@mtthsbrr and @oex-pbi and @rG-tom and @paulinbar and @davidiseminger -- I'm closing this issue.

**Closed by maggiesMSFT** 2021-03-09 02:40 UTC
Labels: Pri2, assigned-to-author, doc-enhancement, powerbi-service/subsvc, powerbi/svc

**Comment by maggiesMSFT** [comment] 2021-03-10 19:19
Great idea, @NickyvVr ! I've added it. Change will be live this afternoon.

**Comment by mihart** [comment] 2021-03-10 23:21
Thanks @teddybercovitz
