### ISSUE TITLE
How does Power BI Pro compare to the Premium SKUs?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/powerbi-docs#3871] opened 2022-06-10 14:17 UTC
It would be very useful if the [Capacity nodes chart](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is#capacity-nodes) included capacity for Power BI Pro. Does pro have higher limits in some areas? I am specifically interested in "Max memory per query" today.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is)
* Content Source: [powerbi-docs/enterprise/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment] 2022-06-10 15:00
Thanks for your comment, @jonwbstr. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment] 2022-06-12 13:10
Hi @jonwbstr,

The Power BI Pro license is intended for individual use. You can see a list of the features it supports in the [Power BI pricing](https://powerbi.microsoft.com/en-us/pricing/#features-compare-charts) page. There's also some more information here:

* [Power BI service features by license type](https://docs.microsoft.com/power-bi/fundamentals/service-features-license-type)

* [Purchase and assign Power BI Pro user licenses](https://docs.microsoft.com/power-bi/enterprise/service-admin-purchasing-power-bi-pro)

* [License types and capabilities](https://docs.microsoft.com/power-bi/enterprise/service-admin-licensing-organization#license-types-and-capabilities)

In any case, the Power BI Pro license doesn't have higher limits than any of the Premium SKUs.

Hope this helps,

Kesem

**Comment by jonwbstr** [comment] 2022-06-12 15:13
Read the question, how does power bi pro max mem per query compare, compare
compare to the roof sku's

You just said pro doesn't have a max mem than any of the premium sku's.
Does it have a lower max mem? Is it the same as any of the premium sku's?

What about the other resource limits?

It would be nice to know!

**Comment by KesemSharabi** [comment] 2022-06-16 14:24
Hi @jonwbstr,

After checking with the engineering team, I can confirm that the 'Max memory per query' for Pro, is 1GB.

Hope this helps,

Kesem

**Comment by jonwbstr** [comment] 2022-06-16 21:49
Hi Kesem, the purpose of this ticket is to help improve the article.

My feedback is that the article would benefit from including the resource limits of Power BI Pro, or some sort of language that commutates to the reader what to expect when moving their reports from a Pro workspace to a Premium workspace.
When the information is added to the article is when it reaches its peak helpfulness.

Question: Does Power BI Pro have a lower max mem? Is it the same as any of the premium sku's?
Answer: 1GB

Question: What about the other resource limits?
Answer: ?

Based on the information you have shared we have opened a ticket with the PowerBI team because we have a report that is failing to refresh when in a Premium workspace, and refreshes successfully in a Pro workspace.

**Comment by KesemSharabi** [comment] 2022-06-22 13:24
Hi @jonwbstr,

Thank you for your feedback and for getting involved.

In the future we'll consider adding Pro to this table. As explained before, the Pro vs Premium is more of a feature comparison rather than a resource and limitations comparison. In any case, we'll add that to our list and talk to the product team about adding additional information regarding the Pro licesne.

Thanks again and hope you figure out what's causing your problem quickly!

Kesem

**Closed by KesemSharabi** 2022-06-22 13:24 UTC
Labels: assigned-to-author, powerbi/svc, pri1, powerbi-premium/subsvc

**Comment by jonwbstr** [comment] 2022-06-30 15:54
Hi @KesemSharabi, Is the pro vs premium feature comparison page you referenced something I can view today?
Also, I opened a support ticket and according the the engineer I spoke to says the capacity for Pro doesn't work quite the way the person from the product team you spoke to described it.

According to support, in a Pro workspace the resources are shared with everyone else in the region and they are not sure what the upper and lower limits but was able to confirm the _potential_ 'Max memory per query' is greater than 1GB.

This makes planning for a transition from Pro to Premium a little trickier than I initially expected. The search continues for reading material that helps us along the journey of moving a report from PowerBI pro to PowerBI Premium!

**Comment by jonwbstr** [comment] 2022-07-08 20:32
While reviewing this project I came across
https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-what-is

Pretty sure I'm working with Gen2 capacity, not sure how I wound up in the Gen1 article.

These two sections hold a lot more significance in light of the above discussions.

> Memory restrictions are different in Premium Gen2 and [Embedded Gen 2](https://docs.microsoft.com/en-us/power-bi/developer/embedded/power-bi-embedded-generation-2). In the first generation of Premium and Embedded, memory was restricted to a limited amount of RAM used by all items simultaneously running. In Gen2, there is no memory Limit for the capacity as a whole. Instead, individual items (such as datasets, dataflows, paginated reports) are subject to the following RAM limitations

and

> ... consider a dataset with an in-memory footprint of 1 GB, and a user initiating an on-demand refresh while interacting with a report based on the same dataset. Two separate actions determine the amount of memory attributed to the original dataset, which may be larger than two times the dataset size ...

Support says the memory available for a refresh command is sku capacity - all datasets in the capacity. The gen2 article says it's per dataset.
