### ISSUE TITLE
Can not follow a specific step of this tutorial.

### ISSUE THREAD

**Issue by yaseenrao** [MicrosoftDocs/powerbi-docs#3638] opened 2022-02-27 02:13 UTC
Hi,
I'm following this tutorial 
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-dimensional-model-report#visual-2-sales-amount-by-date

The 6th step of the tutorial has you changing the data color, but it seems that in the latest version of Power BI (Version: 2.102.683.0 64-bit (February 2022)) this feature has been changed.

Hence this step can not be followed for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 751771a8-ae97-2f7a-45f7-6eab5e30bb98
* Version Independent ID: 69b8d8ce-49e3-feb2-b751-c9a3c26bc501
* Content: [Tutorial: From dimensional model to stunning report in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-dimensional-model-report)
* Content Source: [powerbi-docs/create-reports/desktop-dimensional-model-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-dimensional-model-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment] 2022-02-28 17:05
Hi @yaseenrao, thanks for your feedback. I will look into the issue and correct the docs. Thanks!

**Comment by paulinbar** [comment] 2023-06-21 12:05
Hi @yaseenrao, I tried this, and was unable to reproduce the problem you mentioned? Is the option to change the data color still missing for you? In the meantime I am closing this issue, but please feel free to reopen it if you are still experiencing the problem. Thanks.

**Closed by paulinbar** 2023-06-21 12:05 UTC
Labels: doc-bug, powerbi/svc, pri1, pbi-reports-dashboards/subsvc
