### ISSUE TITLE
No DNS record found for service telemetry

### ISSUE THREAD

**Issue by cchapin2020** [MicrosoftDocs/powerbi-docs#4023] opened 2022-08-24 15:50 UTC
[Enter feedback here]
The Service Telemetry hostname in the table does not resolve:
dc.services.visualstudio.us

Resolve-DnsName dc.services.visualstudio.us
Resolve-DnsName: dc.services.visualstudio.us : DNS name does not exist.

Should this host be able to resolve in DNS publicly or is this the incorrect hostname?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-govus-overview#power-bi-urls-for-general-site-usage)
* Content Source: [powerbi-docs/enterprise/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment] 2022-08-24 17:00
Thanks for your comment, @cchapin2020. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment] 2022-08-24 19:17
Hi @cchapin2020 - I believe the behavior you're seeing is by design, but I will verify with the engineering team, just in case there's a typo. The parent domain - visualstudio.us - does resolve with NSLookup.

**Comment by kfollis** [comment] 2022-08-24 21:08
@cchapin2020 - for context: are you testing the connectivity from within a government cloud environment. If so, which one? Are you experiencing connectivity issues, or are you simply validating the endpoints?

**Comment by cchapin2020** [comment] 2022-08-25 15:02
I am validating endpoints for the CX to configure their firewall access from on-prem to Azure. This is not in a gov cloud environment, the GCC environment is in Azure Commercial.

**Comment by kfollis** [comment] 2023-07-14 17:09
If you are continuing to experience issues, please contact support to escalate. Closing this issue.

**Closed by kfollis** 2023-07-14 17:09 UTC
Labels: assigned-to-author, powerbi/svc, powerbi-admin/subsvc, Pri2
