### ISSUE TITLE
Setting alerts now require signing up for Fabric

### ISSUE THREAD

**Issue by Faz-z** [MicrosoftDocs/powerbi-docs#4844] opened 2023-11-02 07:55 UTC
[Enter feedback here]
I can not create an alert with my pro license as it now requires you to sign up for the Fabric.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85f64d2d-e9b8-59f1-afc1-8d94e2f3c1bd
* Version Independent ID: 565fdc0b-2462-806c-7c17-d189d2378ba4
* Content: [Tutorial:Set data alerts on the Power BI service dashboards - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-alerts#who-can-set-alerts)
* Content Source: [powerbi-docs/consumer/end-user-alerts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-alerts.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment] 2023-11-02 09:01
Thanks for your comment, @Faz-z. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment] 2023-11-13 18:35
Hi @Faz-z ,
I see that you have also posted on Community :-)  I have not been able to reproduce your issue.  I have a Pro license and am able to create and manage alerts without receiving an error message.  Since you do have a paid subscription, I suggest contacting Support since this doesn't appear to be a documentation issue.  
All the best,
The DOCS team

**Closed by mihart** 2023-11-13 18:35 UTC
Labels: assigned-to-author
