### ISSUE TITLE
Totally wrong documentation

### ISSUE THREAD

**Issue by elfigha** [MicrosoftDocs/powerbi-docs#4065] opened 2022-09-18 12:38 UTC
[Enter feedback here]

_**"You only see the Save a copy option [[Build permission](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions)] if app permissions grant Build permission for the underlying dataset, and allow users to make copies of the report."**_

I created a WS workspace and two users User1 and User2
User1 is Admin of WS and publishes a ReportXY .pbix file there.
User1 grants Build permission to User2 on ReportXY
User2 doesn't see the ReportXY anywhere to make a copy of it with Copy As.
The correct procedure is to share ReportXY with User2 and grant him at least build permission
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports)
* Content Source: [powerbi-docs/connect-data/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment] 2022-09-18 13:00
Thanks for your comment, @elfigha. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment] 2022-09-19 08:04
Hi @elfigha, thanks for your feedback. Let me check this out in more detail and I will correct the documentation as necessary.

**Comment by paulinbar** [comment] 2023-06-11 12:20
HI @elfigha, sorry for the delayed response. In your description above, you write: "User1 grants Build permission to User2 on ReportXY". How did you grant this permission? Explicitly, through manage permissions? I think the issue is that in order to see the report, you need read permissions. If you granted build permission through manage permissions, that wouldn't include read permissions. You mentioned sharing the report as the correct way to do this. It is true that with sharing, you can give both read and build permission, but you could also do this by giving the user at least the Contributor role in the workspace that has the dataset. I think for the documentation, we need to specify that read permission on the dataset is a prerequisite.

**Comment by paulinbar** [comment] 2023-07-20 14:46
Hi @elfigha, I have been working with this scenario, and I think the documentation is not wrong, but it is not explicit enough. You need to have access to the workspace in order to see the report in order to copy it. The documentation mentions having workspace roles - and that would grant access to the workspace roles that would allow you to get to the report that you have permissions to copy. Without a role allowing access to the workspace, you won't be able to get to the report. In that case, you can create the copy by sharing the report, as you mentioned. I will think about ways to update the documentation to be more explicit about why the workspace role is important. In any event, I am closing this issue now. Feel free to reopen if you feel the need. Thanks!

**Closed by paulinbar** 2023-07-20 14:46 UTC
Labels: assigned-to-author, powerbi/svc, Pri2, pbi-data-sources/subsvc
