### ISSUE TITLE
Error on running Python script on Power BI--ErrorCode=-2147467259

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1495] opened 2019-10-09 20:07 UTC
Hi team, 
I'm moving this here https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/42
because it may be related with the original documentation

@linxurong commented 8 days ago — with docs.microsoft.com
I found a error most of time when I run a python script on Power BI, how to solve this issue

DataSource.Error: ADO.NET: A problem occurred while processing your Python script.
Here are the technical details: Process must exit before requested information can be determined.
Details:
DataSourceKind=Python
DataSourcePath=Python
Message=A problem occurred while processing your Python script.
Here are the technical details: Process must exit before requested information can be determined.
ErrorCode=-2147467259
ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonUnexpectedException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Run Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-scripts#feedback)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by srigney2142** [comment] 2019-10-10 18:19
Thanks for your comment, @CeciAc I've assigned this issue to the doc author for review.

**Comment by pouyanebrahimi** [comment] 2019-11-13 20:46
Did you get answer for this issue?

**Comment by otarb** [comment] 2019-11-13 22:07
Are there any more details about environment or when this happens? 

Which version of Python is being used
In which cases does this happen, preferably a script that reproduces the error

**Comment by pouyanebrahimi** [comment] 2019-11-14 03:02
@otarb 
The python version is: wWinpython64-3.7.4.0
The PowerBi version is: Power BI Desktop (September 2019) 

This is what I have done:
1. loading a csv file into Power BI
2. then, home>Edit Querries> this will open a new window. In this window, I went to Transform> Run Python Script > after choosing that, a new window opens that I am supposed to write a python code. I tried different options such as: no code, or a simple code (import pandas as pd; df=pd.DataFrame(dataset)). None of them works! 

Please let me know if you have any suggestion. 
Thanks,

**Comment by pouyanebrahimi** [comment] 2019-11-14 21:10
@CeciAc, @srigney2142 , @otarb 
Do you have any thought on this subject? Please share if you do.

**Comment by otarb** [comment] 2019-11-14 23:35
@pouyanebrahimi 

make sure that python installation selected in options page is what you expect 
![image](https://user-images.githubusercontent.com/17887981/68904838-c929c980-06f3-11ea-9323-9108e3782c0f.png)

you can also try using python.exe (from your installation folder, selected in the dropdown above) outside PowerBI to make it's sure that issue is not with your python installation

alternatively, you could also try running with basic python https://www.python.org/downloads/ and see how that works

**Comment by linxurong** [comment] 2019-11-15 01:33
Thanks for all your help.&nbsp;
I uninstall and re-install the python, then problem solved and it work properly.&nbsp;



Best Regards
Sean Lin


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Otar Bichiashvili"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月15日(星期五) 上午7:35
收件人:&nbsp;"MicrosoftDocs/powerbi-docs"<powerbi-docs@noreply.github.com&gt;;
抄送:&nbsp;"Sean"<linxurong@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MicrosoftDocs/powerbi-docs] Error on running Python script on Power BI--ErrorCode=-2147467259 (#1495)




@pouyanebrahimi
 
make sure that python installation selected in options page is what you expect
 
 
you can also try using python.exe (from your installation folder, selected in the dropdown above) outside PowerBI to make it's sure that issue is not with your python installation
 
alternatively, you could also try running with basic python https://www.python.org/downloads/ and see how that works

**Comment by otarb** [comment] 2019-11-15 02:06
happy to hear that

closing the issue since problem is resolved

**Comment by otarb** [comment] 2019-11-15 02:06
#please-close

**Closed by otarb** 2019-11-15 02:06 UTC
Labels: assigned-to-author, doc-enhancement, powerbi-desktop/subsvc, powerbi/svc, pri1

**Comment by pouyanebrahimi** [comment] 2019-11-15 02:09
@otarb 
LoL I have not fix issue yet! @linxurong  is another user! 
Since I am using the company labtop, I am not able to uninstall and reinstall the python. I should fill some request.

**Comment by otarb** [comment] 2019-11-15 02:19
Issue was originally opened for @linxurong, and that problem is now resolved

If you feel like you have similar, but still a different problem, please file a separate issue.  

In the meanwhile, based on the information you gave me, it's a problem with your Python installation, or way your environment is set up. If for your python environment to be ready, you have run some extra steps (few distributions of Python do this, by creating a shortcut which underneath opens python with extra options, settings or commands, to either import libraries, path or any other action that's necessary to prepare environment), this can be a problem. PowerBI will directly use python executable in installation folder. If you have extra steps required, you need to make sure they are run when python executable is launched.
