### ISSUE TITLE
Forecasting Algorithm

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2305] opened 2020-06-18 16:55 UTC
Can you please provide more information about the forecasting algorithms used for creating the forecasts? Or provide link if that information is available elsewhere in Power BI documentation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Use the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-analytics-pane)
* Content Source: [powerbi-docs/transform-model/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment] 2020-06-19 21:20
Thanks for the question, @pawarbi. I'm assigning to the author to see if we have more information available.

**Comment by SharpWhite** [comment] 2020-10-30 14:23
Looks like this is a duplicate of #2203 where @pawarbi provided a link to this article:
[Introducing new forecasting capabilities in Power View for Office 365](https://powerbi.microsoft.com/en-us/blog/introducing-new-forecasting-capabilities-in-power-view-for-office-365/).

There is another Microsoft article here:
[Describing the forecasting models in Power View](https://powerbi.microsoft.com/en-us/blog/describing-the-forecasting-models-in-power-view/) 
and this includes details about the actual forecasting algorithms used.

Both articles are referring to Power View, but they appear on the Power BI blogs, and come up in web searches for Power BI forecasting, so I assume the forecasting information applies to Power BI, but it would indeed be helpful to have this confirmed, and added to the official documentation page if so.

**Closed** 2021-03-16 16:34 UTC
Labels: Pri2, doc-enhancement, powerbi-desktop/subsvc, powerbi/svc, pri1
