### ISSUE TITLE
embed URL has extra parameters

### ISSUE THREAD

**Issue by ChipDale66** [MicrosoftDocs/powerbi-docs#2709] opened 2021-01-04 14:40 UTC
the secure embed code is obtained from a new menu item called Share, it is no longer on the ... menu

Also, the URL has extra parameters to those shown in your example

the screen shot of your example has the URL showing just a reportId and &autoAuth=true
e.g. https://app.powerbi.com/reportEmbed?reportId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&autoAuth=true

however, when I get the embed code it has extra parameters, &ctid and &config and &appId for a report in an APP, or &groupId for a report from a workspace

https://app.powerbi.com/reportEmbed
?reportId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
&appId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
&autoAuth=true
&ctid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
&config=12345678901234567890123456789012345678901234

https://app.powerbi.com/reportEmbed
?reportId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
&groupId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
&autoAuth=true
&ctid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
&config=12345678901234567890123456789012345678901234

I published a link in December and it now does not work as the &config value is different. 

What do these parameters do?

**Comment by ChipDale66** [comment] 2021-01-04 14:44
sorry, this has lost the link to the page
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-secure

**Comment by ChipDale66** [comment] 2021-01-05 12:37
i have raised a second issue against the actual page https://github.com/MicrosoftDocs/powerbi-docs/issues/2710

**Comment by maggiesMSFT** [comment] 2021-01-05 18:27
Hi, @ChipDale66 -- unless I'm missing something, this is a duplicate of https://github.com/MicrosoftDocs/powerbi-docs/issues/2710. So I'm closing this one, and I'm working on getting answers to 2710. 
Thanks!

**Closed by maggiesMSFT** 2021-01-05 18:27 UTC
Labels: Pri3
