### ISSUE TITLE
Either content is old, or PBI has a bug hiding the share icon

### ISSUE THREAD

**Issue by kristyler** [MicrosoftDocs/powerbi-docs#2653] opened 2020-11-30 17:09 UTC
The share icon is missing. My records from a week ago had it on the workspace page. This site shows it on the report page. I cannot find the share icon as of now.

Updates, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df058604-4117-88d8-0cb0-935d08e5b22a
* Version Independent ID: dc8d3604-1fea-0109-2a94-13bd70a10522
* Content: [Ways to collaborate and share in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports)
* Content Source: [powerbi-docs/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment] 2020-11-30 20:33
Hi, @kristyler -- this issue looks like a duplicate of https://github.com/MicrosoftDocs/powerbi-docs/issues/2655 -- or vice versa! So I think you need to enter a support issue for it.
https://powerbi.microsoft.com/en-us/support/
Hope that helps!

**Closed by maggiesMSFT** 2020-11-30 20:33 UTC
Labels: bug, powerbi-service/subsvc, powerbi/svc
