### ISSUE TITLE
My users cannot see the Copy icon

### ISSUE THREAD

**Issue by judemoore** [MicrosoftDocs/powerbi-docs#1305] opened 2019-08-07 09:43 UTC
Hi Power BI Team
My users cannot see the "Copy" icon, despite having: 1) Workspace - Viewer access,  2) Dataset both Viewer and Build rights too.
a) If there a tenant permission or something missing too?
b) Does it need to be a published App workspace  aka App(build) permission too ?
Kind Regards
Jude

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other workspaces (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-copy-reports#feedback)
* Content Source: [powerbi-docs/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment] 2019-08-07 14:58
Thanks for your comment, @judemoore. I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment] 2019-08-09 18:33
Hi, @judemoore -- do your users have Pro licenses?

**Comment by maggiesMSFT** [comment] 2019-08-09 19:24
Ah -- the Viewer role. That is not enough to copy a report. They need at least the Contributor role.

**Comment by ZenoLv** [comment] 2019-08-15 07:42
> Hi, @judemoore -- do your users have Pro licenses?

Hi @maggiesMSFT I'm facing the same issue and yes they have Pro license, because free users cannot access any App workspace. 

And the document mentioned only V2 worksapce can see the copy icon which is not true, V1 also can see the icon, but the problem is if user don't have permission to edit the workspace, he cannot copy it successfully.

**Comment by judemoore** [comment] 2019-08-15 11:58
Hi Michael and all

Yes they have Pro licences.

I thought the whole point of the “build” permission was so that the users can build reports without having access to change the original production reports though. Kind of defeats the process otherwise to have to provide the “Contribute” workspace access.

I got it working in the end.

I had to delete the original release of the app, then publish the workspace as an app again.

Then, on the last page, put a tick in the box to “allow reports to be crated using the datasets”.

See number 3.
https://docs.microsoft.com/en-us/power-bi/service-datasets-build-permissions

I still could not however, provide viewer only  direct workspace access to allow them to build reports.

Thanks for all your inputs though

Regards
Jude

Sent from my iPhone

On 7 Aug 2019, at 15:58, Michael Blythe <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your comment, @judemoore<https://github.com/judemoore>. I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment] 2019-08-16 18:58
Hi, @judemoore -- sounds like you sorted out your issue. Thanks for letting us know.
And hi, @ZenoLv -- shared datasets is only supported for v2 workspaces, so if you're seeing something else, that's a bug...

**Closed by maggiesMSFT** 2019-08-16 18:58 UTC
Labels: Pri2, assigned-to-author, doc-enhancement, powerbi-service/subsvc, powerbi/svc, product-question

**Comment by sjs210** [comment] 2020-08-12 18:45
Does the copy report functionality work on users who are accessing the online service using a tablet?  It appears (although I'm not sure!) to not be allowed on mobile devices, and if that is the case, it would be helpful to add that to the documentation.  Thank you!
