### ISSUE TITLE
Audit Log / Viewed Power BI Reports & Dashboards only shows authenticated users

### ISSUE THREAD

**Issue by ShaneOss** [MicrosoftDocs/powerbi-docs#2448] opened 2020-08-25 22:33 UTC
The audit log activities for Viewed Power BI Reports and Viewed Power BI Dashboards, only shows authenticated users. How can details of non authenticated users who may have viewed reports/dashboards be reported on?

E.g. something like...
CreationDate | UserIds | Operations | AuditData
-- | -- | -- | --
2020-08-24T05:05:34.0000000Z | Unknown | ViewReport | {"Id":"594dda1c-9cf8-406c-ab8e-cd88fb5fccd9","RecordType":20,"CreationTime":"2020-08-24T05:05:34","Operation":"ViewReport","OrganizationId":"12537282-45d7-4981-73fb-c2da6e835c71","UserType":4,"UserKey":"Unknown","Workload":"PowerBI","UserId":"Anonymous","ClientIP":"1.42.237.166","UserAgent":"Mozilla\/5.0   (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko)   Chrome\/64.0.3282.140 Safari\/537.36   Edge\/17.17134","Activity":"ViewReport","ItemName":"TEST_20200822","WorkSpaceName":"TEST [Development]","DatasetName":"TEST_20200822","ReportName":"TEST_20200822","CapacityId":"421F77C0-D7A5-48CE-1A0F-CFAB5FC39D01","CapacityName":"TEST","WorkspaceId":"44eb86f7-ac43-1f73-9b7f-101b20805483","AppName":"TEST App","ObjectId":"TEST_20200822","DatasetId":"c4e5a7a9-1649-4384-ac17-cd9a818830cf","ReportId":"7b80e9a1-e002-1050-881e-21166ed940d4","IsSuccess":true,"ReportType":"PowerBIReport","RequestId":"db19f4b1-3578-b0f3-0f54-c0cedc6612d8","ActivityId":"f0281a01-84fd-4aab-be9e-133ca50311d9","AppReportId":"456b8656-b898-598a-943b-4169c97eb059","DistributionMethod":"Apps","ConsumptionMethod":"Power   BI Web"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing#operations-available-in-the-audit-and-activity-logs)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment] 2020-08-25 23:00
Hi @ShaneOss - Thanks for the question! I'll have to do a little research on this to see if that's possible. I'll check with the engineering team and follow up with what I find out.

**Comment by ShaneOss** [comment] 2020-09-02 01:18
Thanks Kate. Also logged a premier ticket (120090223000126) for it.

**Comment by kfollis** [comment] 2020-09-03 20:18
Can you provide a little more info about your scenario and what info is missing? The support agent is looped into the conversation, but I want to be sure I'm asking the right question of engineering.

**Comment by ShaneOss** [comment] 2020-09-03 22:55
Sure. We're looking for external/anonymous users who may have viewed Power BI reports/dashboards that were published to the web. In the current Audit Log reports we can only see authenticated users listed, not non-authenticated users.

Users who confirmed they viewed reports/dashboards via the web with no sign in required, do not appear in the logs.
Thanks! Let me know if you need any more information.

**Comment by kfollis** [comment] 2020-09-03 23:04
Thank you!

**Comment by kfollis** [comment] 2020-09-23 21:40
Tracking with support and see that the ticket is now resolved as "by design" with the requested capability added to backlogs. Closing the issue. Thanks!

**Closed by kfollis** 2020-09-23 21:40 UTC
Labels: Pri2, powerbi-admin/subsvc, powerbi/svc
