### ISSUE TITLE
Link to May 2020 version leads to 404 page

### ISSUE THREAD

**Issue by tconrady** [MicrosoftDocs/powerbi-docs#2664] opened 2020-12-03 14:12 UTC
Trying to download the May 2020 32 or 64 bit version leads to a 404 page instead of the setup exe. The April 2020 entry does not have any links at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment] 2020-12-04 01:06
@tconrady - I was unable to reproduce the error with the May 32-bit and 64-bit installation links. I did receive an MSI file when clicking those links. Have you tried again? It's possible the April versions are no longer available, but I'll assign this to the author of the article to check into it.

**Comment by mihart** [comment] 2021-03-11 04:41
Hi @tconrady , 
Thank you for your suggestion.  I wasn't able to reproduce this either.  If the problem persists on your end, please check with the Power BI Community (community.powerbi.com) or contact Support. 
All the best,
The DOCS team

**Closed by mihart** 2021-03-11 04:41 UTC
Labels: Pri2, in-progress, pbi-fundamentals/subsvc, powerbi/svc
