### ISSUE TITLE
Where can I download the House Pricing data?

### ISSUE THREAD

**Issue by SirWm** [MicrosoftDocs/powerbi-docs#1537] opened 2019-10-21 19:43 UTC
Please point me (wharper@otterbein.edu) to where I can download the Key Influencer House Pricing data.  I have googled w/o success.  Thanks!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by srigney2142** [comment] 2019-10-23 17:40
Thanks for your comment, @SirWm This looks like a product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by mgblythe** [comment] 2019-11-01 20:10
@SirWm - assigning to the author to review.

**Comment by juluczni** [comment] 2019-11-07 19:40
You can find the dataset on Kaggle :) https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

**Comment by kfollis** [comment] 2020-11-10 22:49
@mihart - Please consider whether to link to this data source from the article. You may then close this issue as the customer question has been answered.

**Comment by mihart** [comment] 2020-11-18 03:01
@msftrien - please see Kate's question above.

**Comment by msftrien** [comment] 2020-11-18 23:38
@juluczni is there anything preventing us from including the dataset in the docs? Some legal consideration, etc? If not, I think it would be useful to provide a download link so that users can follow along.

**Comment by juluczni** [comment] 2020-11-19 14:09
Yep the license of the dataset is public domain so we are good to share!

**Comment by kfollis** [comment] 2021-02-24 22:31
The article has been updated to include a link to the source data and will publish soon. Thank you for your contribution!

**Closed by kfollis** 2021-02-24 22:31 UTC
Labels: assigned-to-author, doc-enhancement, powerbi-service/subsvc, powerbi/svc, pri1
