### ISSUE TITLE
The section referenced no longer exists

### ISSUE THREAD

**Issue by rihoughton** [MicrosoftDocs/powerbi-docs#4167] opened 2022-11-01 21:57 UTC
This is from the documentation:
![image](https://user-images.githubusercontent.com/99290906/199349618-017adcc7-1e28-4762-88ff-8dea860bb8f4.png)

This is from the app:
![image](https://user-images.githubusercontent.com/99290906/199349659-502e3079-abd4-406b-8729-5dc2df5c464d.png)

Could you please update the documentation so that it references the sections that still exist?

**Comment by kfollis** [comment] 2022-11-01 22:50
Hi @rihoughton - is this the article that you are referencing: https://learn.microsoft.com/en-us/power-bi/enterprise/aggregations-auto-configure? I'm assigning to the writer to comment, but want to be sure that you have reviewed the requirements listed here https://learn.microsoft.com/en-us/power-bi/enterprise/aggregations-auto#requirements for the auto aggregation feature. Thank you for taking the time to submit feedback!

**Comment by rihoughton** [comment] 2022-11-01 22:52
> Hi @rihoughton - is this the article that you are referencing: https://learn.microsoft.com/en-us/power-bi/enterprise/aggregations-auto-configure? I'm assigning to the writer to comment, but want to be sure that you have reviewed the requirements listed here https://learn.microsoft.com/en-us/power-bi/enterprise/aggregations-auto#requirements for the auto aggregation feature. Thank you for taking the time to submit feedback!

Yes, that's the article I am referencing.

**Comment by Minewiskan** [comment] 2022-11-10 18:21
Duplicate of https://github.com/MicrosoftDocs/powerbi-docs/issues/4153

**Closed by Minewiskan** 2022-11-10 18:21 UTC
Labels: Pri3
