### ISSUE TITLE
"supportsHighlight": true is not working

### ISSUE THREAD

**Issue by ek-work** [MicrosoftDocs/powerbi-docs#4857] opened 2023-11-09 19:38 UTC
After adding property `"supportsHighlight": true` in the capabilities.json file the `highlights array property` I expect is not available during update
- Edit interactions is turned on
- I click on another visual in edit mode, and I click on the highlight icon on my custom visual
- I select a value or values in the other visual
- After this, I do get all values, regardless of the selections made in other visuals, but I also expect the `highlights` array property
- **result: dataViews[0].categorical.categories[0] has `{identity, identityFields, source, values}` - but `highlights` is never included**
- according to this documentation page, `Table data view mapping doesn't support the highlights feature.`, but my capabilities file uses `categorical data view mapping` . . .
```
...
"categorical": {
                "categories": {
                    "select": [{
                            "bind": {
...
```
- In an old thread on stackoverflow, there is an indication you have to add interactivity-utils -https://stackoverflow.com/questions/44283091/supportshighlight-setting-ignored-in-capabilities-json-custom-visual-still-re 
  - I've done that too, but there's no mention of that in this page
- In feedback related to this page, there is an [old issue from 2020](https://github.com/MicrosoftDocs/powerbi-docs/issues/2028), which refers to a [sample usage of highlight](https://github.com/microsoft/powerbi-visuals-linedotchart/blob/master/src/visual.ts#L384), but it's using older APIs
- I'm using more recent versions of the powerbi APIS:
```
    "powerbi-visuals-api": "5.3.0",
    "powerbi-visuals-utils-dataviewutils": "6.0.1",
    "powerbi-visuals-utils-formattingmodel": "5.0.0",
    "powerbi-visuals-utils-formattingutils": "6.0.1",
    "powerbi-visuals-utils-interactivityutils": "6.0.1",
    "powerbi-visuals-utils-typeutils": "6.0.1",
```

Is there any way to determine why `highlights` are not available in my visual? Are there other constraints that would cause it to not deliver highlights during update? 

When I read this support page, I understand to get the `highlights array property` all that is required is to add `"supportsHighlight": true` in the capabilities.json, but at least in my case it's not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80303b53-8f3f-e9d3-f00c-1316b44432ee
* Version Independent ID: 774a462b-8188-ebaf-ee87-863c4c0947c4
* Content: [Highlight data points in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/highlight?tabs=Highlight)
* Content Source: [powerbi-docs/developer/visuals/highlight.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/highlight.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment] 2023-11-09 20:01
Thanks for your comment, @ek-work. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment] 2023-11-12 11:59
Thanks for your question, @ek-work. I've forwarded it to our engineers and we'll update the document, if necessary.

**Comment by ek-work** [comment] 2023-11-13 16:11
Thanks @bishalgoswami and @mberdugo 

In further testing, I have found that in my custom visual, if I add only category fields, then I do not get ` dataView.categorical.values[0].highlights`, but if I add a numeric value, then I do get `highlights.`

The problem there is that to a user of this visual (it is a map custom visual), they may only select category of `US state` for example, and when they click on a separate visual for that - and they have selected `highlight` on my custom visual - there is no opportunity for me to implement highlight. I could if the selected categories were passed back (as highlights) during the visual update, but it doesn't seem like that is possible. Is it?

**Comment by mberdugo** [comment] 2023-11-30 16:12
Hi @ek-work. That's a good question. I'll try to find out for you.

**Comment by AleksSavelev** [comment] 2024-01-04 15:12
Hi @ek-work. I'm sorry for the delay.

Is it possible to provide us with the source code of the visual? Since it works fine on my end. Also, it would be good to have a sample report.

**Comment by ek-work** [comment] 2024-01-08 15:37
Hi @AleksSavelev , 
I'm not able to share the code of the visual I'm referencing (private repo in our company). But I will work on getting a sample visual that I can share which exhibits the same behavior.
BTW the powerbi-visuals api and related libraries are as follows:

    "powerbi-visuals-api": "5.4.0",
    "powerbi-visuals-utils-dataviewutils": "6.0.1",
    "powerbi-visuals-utils-formattingmodel": "5.0.0",
    "powerbi-visuals-utils-formattingutils": "6.0.1",
    "powerbi-visuals-utils-typeutils": "6.0.1",

**Comment by mberdugo** [comment] 2024-01-18 09:53
@ek-work and @AleksSavelev 
Can I get an update as to where this stands? I'd like to close this issue, if possible. Are you still working on this? Have you taken it offline?
Thanks.

**Comment by AleksSavelev** [comment] 2024-01-18 10:41
@mberdugo and @ek-work 
I still wasn't able to reproduce the issue, so I expect to get a sample visual

Some time ago we've implemented this feature in one of our [visuals](https://github.com/microsoft/powerbi-visuals-enhancedscatter), you can try to take a look on the implementation, it was added in [3.0.0 version](https://github.com/microsoft/powerbi-visuals-enhancedscatter/commit/735c92179c3de06308e01d7c5c1bae767ce3f480)

**Comment by ek-work** [comment] 2024-01-18 16:00
@mberdugo 
> @ek-work and @AleksSavelev
Can I get an update as to where this stands? I'd like to close this issue, if possible. Are you still working on this? Have you taken it offline?

Highlighting is a feature we are looking to implement in the future. But other tasks have forced me to put this on the sideburner for now. I still want to create a demo Visual demonstrating the problem, and I hope to get back to it soon.

**Comment by mberdugo** [comment] 2024-01-21 08:07
@ek-work and @AleksSavelev 
Thank you both for your input on this issue. I'm going to close it now.
@ek-work, when you are ready to resume, take a look at the visuals that @AleksSavelev referenced above. If you still have questions, feel free to open a new issue.
Thanks.

**Closed by mberdugo** 2024-01-21 08:07 UTC
Labels: assigned-to-author
