### ISSUE TITLE
Add Report Builder version

### ISSUE THREAD

**Issue by vcarazo** [MicrosoftDocs/powerbi-docs#3324] opened 2021-09-30 21:14 UTC
Hello there,

It would be interesting to add the version of Report Builder associated with the version of Power BI Report Server. Just like you have done with Power BI Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Change log for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @jtarquino
* Microsoft Alias: **jaimeta**

**Comment by maggiesMSFT** [comment] 2022-01-05 22:31
Hi, @vcarazo -- Thanks for your comment! I think we do this already, or I'm misunderstanding what you're asking for. For example, the Change Log entry for September, https://docs.microsoft.com/en-us/power-bi/report-server/changelog#september-2021, lists:
**Power BI Report Server**
- Version: 1.12.7981.11681 (build 15.0.1107.166), Released: December 6, 2021
**Power BI Desktop** (optimized for Power BI Report Server)
- Version: 2.97.2222.0 (September 2021), Released: December 6, 2021 

Or is that not what you mean? I'm closing this; if you're looking for something else, please let me know!

**Comment by vcarazo** [comment] 2022-01-07 07:44
Hi @maggiesMSFT,

 As you said the version of Power BI Desktop is already showed alongside with the version of power BI Report Server. I was **not** talking about Power BI Desktop.

I was talking about **Report Builder**, the software client we use to create **paginated reports** (https://www.microsoft.com/es-es/download/details.aspx?id=53613).

So in the example you wrote I would like to see:

- Power BI Report Server
  - Version: 1.12.7981.11681 (build 15.0.1107.166), Released: December 6, 2021
- Power BI Desktop (optimized for Power BI Report Server)
  - Version: 2.97.2222.0 (September 2021), Released: December 6, 2021
- **Report Builder**
  - **Versión: 15.0.19611.0, Released: 06/08/2021**

**Comment by maggiesMSFT** [comment] 2022-01-07 17:51
Good point, @vcarazo ! I'll run this by the devs who own maintaining this page.
Thanks!

**Comment by maggiesMSFT** [comment] 2022-01-07 22:19
Hi, @vcarazo -- here's their response:
"The problem is the Report Builder release is not tied to a PBIRS release like the other bits. The version number changes out of band from the releases of Desktop and RS. We have a list of those versions as they are released here:
https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-change-log
I added a link to the Report Builder change log article from https://docs.microsoft.com/en-us/power-bi/report-server/changelog. The update should be live this afternoon Jan 7 Pacific time.
Hope that helps.
Thanks!

**Closed by maggiesMSFT** 2022-01-07 22:19 UTC
Labels: doc-idea, product-feedback, powerbi/svc, powerbi-report-server/subsvc, Pri2
