### ISSUE TITLE
Incremental refresh :-While peforming Join/Merge works on Partition basis

### ISSUE THREAD

**Issue by rushirvk94** [MicrosoftDocs/powerbi-docs#3471] opened 2021-12-09 08:51 UTC
Hi Team ,Myself Rushikesh Power BI support Engineer and recently I worked on case 2108120050001721 for which we created ICM https://portal.microsofticm.com/imp/v3/incidents/details/264421215 there we came to know from Product Team that while performing join/Merge operation on 2 tables which have incremental refresh policy enabled ,power bi service performs join on the basis of unique column used in join condition along with datecolumn or partitions.

Could you please add this point in the document .Customer specifically asked me to update this in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23849d95-194e-b2b1-735a-03aebb56703a
* Version Independent ID: 391f63a3-2b18-3676-a151-d9859df54ad6
* Content: [Incremental refresh for datasets in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-overview)
* Content Source: [powerbi-docs/connect-data/incremental-refresh-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/incremental-refresh-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by mberdugo** [comment] 2021-12-09 15:55
Thanks for your comment, @rushirvk94 
I've assigned this issue to the doc author for review.

**Comment by Minewiskan** [comment] 2021-12-09 18:24
@rushirvk94 - Rushikesh, could you be more clear on what exactly you want clarified in the docs? I can't tell from the ICM and from your description what the issue is, and where, and why any changes to the docs would help clarify the issue.
Thanks

**Comment by Minewiskan** [comment] 2021-12-09 18:52
Moving to internal channels.

**Closed by Minewiskan** 2021-12-09 18:52 UTC
Labels: assigned-to-author, doc-enhancement, powerbi/svc, Pri2, pbi-data-sources/subsvc
